# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_DZ_python', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рэйтинг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
