# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_DZ_python', '0002_auto_20161225_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antemodel',
            name='amount',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='antemodel',
            name='team_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_DZ_python.TeamModel', verbose_name='На команду'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=1000, upload_to='', verbose_name='Аватар'),
        ),
    ]
