# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_DZ_python', '0003_auto_20161227_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='picture',
            field=models.ImageField(
                blank=True,
                max_length=1000,
                upload_to='',
                verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='antemodel',
            name='amount',
            field=models.FloatField(verbose_name='Сумма ставки'),
        ),
        migrations.AlterField(
            model_name='antemodel',
            name='date_of_ante',
            field=models.DateTimeField(verbose_name='Дата ставки'),
        ),
        migrations.AlterField(
            model_name='antemodel',
            name='match_for',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='dj_DZ_python.MatchModel',
                verbose_name='Матч'),
        ),
        migrations.AlterField(
            model_name='antemodel',
            name='team_for',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='dj_DZ_python.TeamModel',
                verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='antemodel',
            name='user_for',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='matchmodel',
            name='date_of_match',
            field=models.DateTimeField(verbose_name='Дата матча'),
        ),
        migrations.AlterField(
            model_name='matchmodel',
            name='participant_1',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='TeamModel_participant_1',
                to='dj_DZ_python.TeamModel',
                verbose_name='Участник 1'),
        ),
        migrations.AlterField(
            model_name='matchmodel',
            name='participant_2',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='TeamModel_participant_2',
                to='dj_DZ_python.TeamModel',
                verbose_name='Участник 2'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='kind_of_sport',
            field=models.CharField(max_length=255, verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='name',
            field=models.CharField(
                max_length=255,
                unique=True,
                verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='quantity_game',
            field=models.IntegerField(
                default=0, verbose_name='Кол-во матчей (всего)'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='quantity_win',
            field=models.IntegerField(
                default=0, verbose_name='Кол-во выигр. матчей'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(
                blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_in_black_list',
            field=models.BooleanField(
                default=0, verbose_name='В черном списке'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(
                default='',
                max_length=15,
                verbose_name='Номер телефона'),
        ),
    ]
